### ISSUE TITLE
NoClassDefFoundError on version 2.6.0

### ISSUE THREAD

**Issue by Sermilion** [p-lr/MapCompose#84]
Yesterday we upgraded MapCompose to 2.6.0 and now wherever we are on a screen that uses MapCompose app gets crashed and throws following exception:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/selects/SelectImplementation;
                                                                                                    	at ovh.plrapps.mapcompose.core.TileCollector$tileCollectorKernel$1.invokeSuspend(TileCollector.kt:220)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9a4d1a, java.util.concurrent.Executors$FinalizableDelegatedExecutorService@14cf04b]
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.selects.SelectImplementation" on path: DexPathList[[zip file "/data/app/~~gjdRlG1VtYPOxnVJS-MEkw==/de.capmo.android.internal.debug-LCtRwpQi0vVrlT3kvLAKYQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~gjdRlG1VtYPOxnVJS-MEkw==/de.capmo.android.internal.debug-LCtRwpQi0vVrlT3kvLAKYQ==/lib/arm64, /data/app/~~gjdRlG1VtYPOxnVJS-MEkw==/de.capmo.android.internal.debug-LCtRwpQi0vVrlT3kvLAKYQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 7 more
```
I reverted the version to 2.5.0 and the issue was gone.

**Comment by p-lr** [comment]
Have you upgraded the Compose BOM to 2023.05.01 ?
Each version of MapCompose is tied to particular version of the Compose BOM.

PS : I would also recommend to upgrade kotlinx.coroutines to 1.7.0

**Comment by Sermilion** [comment]
Hi. Thanks for quick response. Adding explicit coroutine dependency fixed the issue. Appreciate your help and thanks for this great library.
